# Generated by Django 4.2.6 on 2023-11-21 01:22

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('property_title', models.CharField(max_length=200)),
                ('property_description', models.TextField()),
                ('property_feature_status', models.BooleanField(default=False)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Property_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address_street', models.CharField(max_length=200)),
                ('property_address_city', models.CharField(max_length=200)),
                ('property_address_zip', models.CharField(max_length=200)),
                ('property_address_state', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Property_Address',
                'verbose_name_plural': 'Property_Addresses',
            },
        ),
        migrations.CreateModel(
            name='Property_Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_neighborhood_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Property_Neighborhood',
                'verbose_name_plural': 'Property_Neighborhood',
            },
        ),
        migrations.CreateModel(
            name='Property_Price_Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_price_range_name', models.CharField(max_length=200)),
                ('property_price_range_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_price_range_max', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Property_Price_Range',
                'verbose_name_plural': 'Property_Price_Range',
            },
        ),
        migrations.CreateModel(
            name='Property_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_status_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Property_Status',
                'verbose_name_plural': 'Property_Status',
            },
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Property_Type',
                'verbose_name_plural': 'Property_Type',
            },
        ),
        migrations.CreateModel(
            name='Property_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image_location', models.FileField(blank=True, null=True, upload_to=listings.models.adjust_filename)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
            ],
            options={
                'verbose_name': 'Property_Image',
                'verbose_name_plural': 'Property_Image',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.property_address'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.property_neighborhood'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_price_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.property_price_range'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='listings.property_status'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.property_type'),
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_filter_date', models.DateTimeField(auto_now_add=True)),
                ('property_neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property_neighborhood')),
                ('property_price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property_price_range')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property_type')),
            ],
            options={
                'verbose_name': 'Applied_Filter',
                'verbose_name_plural': 'Applied_Filters',
            },
        ),
    ]
